import { Main } from "../components/Main";
import Head from "next/head";
import { Footer } from "../components/Footer";
import styles from "../styles/Home.module.css";
import { Header } from "../components/Header";
import { useCallback, useEffect } from "react";

export default function Home() {
  // const handleClick = useCallback((e) => {
  //   console.log(e.target.href);
  //   e.preventDefault();
  // }, []);

  useEffect(() => {
    console.log("マウント時");
    document.body.style.backgroundColor = "lightblue";
    return () => {
      console.log("アンマウント時");
      document.body.style.backgroundColor = "";
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <a href="/about" onClick={handleClick}>
        ボタン
      </a> */}
      <Main page="index" />
      <Footer />
    </div>
  );
}
